# Generated by Django 4.2.6 on 2024-04-26 02:20

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=api.models.gen_hash_id, max_length=32)),
                ('archive', models.FileField(upload_to=api.models.upload_file_hash_name)),
            ],
        ),
        migrations.CreateModel(
            name='ImageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('raw', models.FilePathField()),
                ('labeled', models.FilePathField()),
                ('is_ready', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.imagearchive')),
            ],
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.FilePathField()),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='api.imagelink')),
            ],
        ),
    ]
