# Generated by Django 4.2.6 on 2024-04-26 02:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagearchive',
            name='archive',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_file_hash_name),
        ),
    ]
