# Generated by Django 4.2.6 on 2024-04-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_imagearchive_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelink',
            name='labeled',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='imagelink',
            name='raw',
            field=models.FilePathField(null=True),
        ),
    ]
