# Generated by Django 4.2.6 on 2024-04-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_imagelink_labeled_alter_imagelink_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='face',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagelink',
            name='labeled',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagelink',
            name='raw',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
